# Generated by Django 4.2.3 on 2023-07-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='short_url',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='time_date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
